version: '3.6'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pastiin_aja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_volume:

